name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: npm install
        run: npm install

      - run: npm i --no-save @sap/cds-compiler uuid nanoid

      - name: npm test
        run: npm test
        env:
          CI: true

      - name: npm shrinkwrap
        run: npm shrinkwrap

      - name: npm auth & publish
        run: npm run build && npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
